services:
  app:
    image: phonebook-frontend
    build:
      context: ./phonebook-frontend
      dockerfile: Dockerfile 
    ports:
      - 80:80
    environment:
      PERSON_URL: http://localhost:3000/api/persons
    depends_on:
      - server  
  server:
    image: phonebook-backend
    build:
      context: ./phonebook-backend
      dockerfile: Dockerfile 
    ports:
      - 3000:3000
    environment: 
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin    
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:       
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js    
      - ./mongo_data:/data/db            
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    container_name: phonebook-reverse-proxy
    depends_on:
      - app
