services:
  app:
    image: phonebook-frontend-dev
    build:
      context: ./phonebook-frontend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./phonebook-frontend:/usr/src/app/phonebook-frontend 
      # For some weird reason, having a separate volume for node_modules was 
      # Required. Without it, Vite was not found
      - /usr/src/app/phonebook-frontend/node_modules       
    ports:
      - 5173:5173
    environment:
      PERSON_URL: http://localhost:3000/api/persons
    depends_on:
      - server  
  server:
    image: phonebook-backend-dev
    build:
      context: ./phonebook-backend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./phonebook-backend:/usr/src/app/phonebook-backend
      # For some weird reason, having a separate volume for node_modules was 
      # Required. Without it, nodemon was not found
      - /usr/src/app/phonebook-backend/node_modules 
    ports:
      - 3000:3000
    environment: 
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin    
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:       
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js    
      - ./mongo_data:/data/db          

